prompts: [prompts.txt]
providers: [openai:gpt-3.5-turbo]
tests:
  - description: Test case - Compare similarity scores
    vars:
      var1: embeddings_df1
      var2: embeddings_df2
    assert:
      - type: function
        value: expected LLM output goes here
      - type: function
        value: compare_similarity_scores(var1, var2)

  # - description: Second test case - manual review
  #   # Test cases don't need assertions if you prefer to review the output yourself
  #   vars:
  #     var1: new value
  #     var2: another value
  #     var3: third value

  # - description: Third test case - other types of automatic review
  #   vars:
  #     var1: yet another value
  #     var2: and another
  #     var3: dear llm, please output your response in json format
  #   assert:
  #     - type: contains-json
  #     - type: similar
  #       value: ensures that output is semantically similar to this text
  #     - type: llm-rubric
  #       value: must contain a reference to X